### ISSUE TITLE
A6 don't connect APN

### ISSUE THREAD

**Issue by adz1122** [vshymanskyy/TinyGSM#13]
I test found A6 don't connect APN,always fail, I used MQTT example, but AT_DBUG is OK

**Comment by vshymanskyy** [comment]
Please provide steps to reproduce, what output you see and what is expected.

**Comment by widoyo** [comment]
I use Diagnostic sketch. Serial monitor stop after "Waiting for Network". I use A6 Module modem with BAUDrate 115200.

```
+CPIN:READ\

OK

+CTZV917/02/17,22911:51,+07

+CIEV: sersice,  1
+CL�V: roam, 0
+CREG: 1Waiting for network...AT+CREG?

+CREGz 1,1

OKAT+CREG?

+CREG9 1,1

OK
	AT+CREG?

�(�Q�'�b�j
OK
AT+CREG?

+CREG9 1,1

OK
	AT+CREG?

+A�EG: 1,1

	OK
AT+CREG?

+A�EG: 1,1

	OK
AT+CREG?

+(�Q�'�b�j

	OK
AT+CREG?

+A�EG: 1,1

	OK
AT+CREG?

+A�EG: 1,1
OK
AT+CREG?

�(�Q�'�b�j
OK
AT+CREG?

+A�EG: 1,1


OK
AT+CREG?

+CREG: 1.1

OK

```

**Comment by GeorgianBorca** [comment]
To me, it looks like you have a lot of noise in there. Try a lower boudrate and shorter cables. Avoid power cables near the data cables.

**Comment by widoyo** [comment]
I use Arduino UNO (5v) without voltage divider on RX of A6. May be thats
the problem.

On 18 Feb 2017 6:10 a.m., "Georgian Borca" <notifications@github.com> wrote:

To me, it looks like you have a lot of noise in there. Try a lower boudrate
and shorter cables. Avoid power cables near the data cables.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/vshymanskyy/TinyGSM/issues/13#issuecomment-280791848>,
or mute the thread

**Comment by widoyo** [comment]
I set lower **BAUDRATE into 9600** and better result.
