### ISSUE TITLE
SIM7020 support

### ISSUE THREAD

**Issue by DiegoMendoza1** [vshymanskyy/TinyGSM#522]
## What type of issues is this?

[ X] Request to support a new module

Modem: SIM7020C
Main processor board: ESP32
TinyGSM version: 0.10.9

Thanks for this great job. I had used this library with SIM800 for a lot of time. Now I am migrating my hardware to SIM7020 but It doesn´t work with. I´ve tried with an old pull request but it doesn´t work. 
Could you give support to SIM7020. 

Thanks a lot

**Comment by SRGDamia1** [comment]
Are you looking at the old fork where https://github.com/bsorgo did a bunch of work on the SIM7020:  https://github.com/bsorgo/TinyGSM?

I don't know if it was ever functional, and it's outdated.  I don't know of others with the 7020 off the top of my head.

I'm going to close this issue since it's a repeat of #278.
