### ISSUE TITLE
knowing Local IP Address

### ISSUE THREAD

**Issue by mushfiq-cse05-buet** [vshymanskyy/TinyGSM#9]
is there any function in TinyGsm class so that i can get the Local IP address assigned by GSM operator after  calling gprsConnect() function ????? 
Thank you!

**Comment by vshymanskyy** [comment]
Which modem model do you need it for?

**Comment by mushfiq-cse05-buet** [comment]
SIM800L please :) @vshymanskyy

**Comment by mushfiq-cse05-buet** [comment]
i think you can add up functions like getLocalIP for eery model :) thanks @vshymanskyy

**Comment by bsiege** [comment]
SIM800//SIM900
Serial3 << (F("AT+CIFSR")) << endl;//get local IP adress
But mostly this will not help because it is CGNAT'ted to public internet.
For public IP you need some external service, which could not longterm reliable and data consuming. In my case i prefer to log sensor IP on the receiver (server) side.
